language: node_js
node_js:
- '10.6'
script:
- bash build.sh
deploy:
  skip_cleanup: true
  on:
    branch: release
  provider: npm
  email: joe.politz@gmail.com
  api_key:
    secure: o8BnblLlSjc0QT89NxDbbaBn/5q1LOFi0JRhiFCqLWw6lwJlEWgg4t6Stnv+/i5sCnnTEnCwdJoB/8OK7nNeQOlfYfwyu/mHGybOOrmTi7+qxL8OlXXDku72BdxTPYmUyB7f8jVDbpt8k3TL76YWpi8s+h9O0sUELM8QVaT2CI2nLNFdmzwErUSOJF5+SP+Eeo2XclQt1BvoM6V/GKb6XBDx4zV+gXinjyCggb6bNPdbvbQ0zXbVrSR0Dxrzuj9E3o16DhPkP8wvNH4ujAfZhDKvZ05MgxMecjUXuBJgTS84L5DS10HapQfB9VgRWvgoa/oeP60xBLDGjc6I66eP3UyxQkjC4AHyuXLkZreL88kjMgD1yGTkIlY7uvEgr/uzj1WqTuc9Ngwiaf/y5sxHmTA1rly68sYalNLAtmA+eGjfWg6qRd6ZuECdrBb+Yurn/VKidOdm1HPuS4OiVN+mKG0KrBDmwcIVt9Vw3RjqmnUDuGB1cGWVUvXwcPou66i8m2a7OMPlpPFbTSbWy3CuoUIasfDx1toGO0W3Pvwrqd1kZ1gMHZKQJKrYxvZixUXxFkT51GlnLdXyrky8So9e697vZx5exWqvVem8t9wHOEAvRxEDi0XIFGh/4jectyDoZGdDa4RjA/au2+B9jVi6kDa0zlmRImg4v7BoZM2hEVY=
